# A Service provider for managing HTTP Sessions
# in a Supranim application.
#
#   (c) 2025 George Lemon / Made by Humans from OpenPeeps
#   https://supranim.com | https://github.com/supranim
#   
#   Released under the MIT License.

import pkg/supranim/core/servicemanager
import pkg/libsodium/[sodium, sodium_sizes]
import pkg/supranim/core/paths

initService HttpSession[Singleton]:
  # config -> ConfigHttpSession
  backend do:
    import std/[times, json, tables, hashes]
    import pkg/supranim/support/[cookie, nanoid]
    export cookie

    type
      # Configuration Objects
      ConfigHttpAuthenticationResetPassword* = object
        enable: bool = true
          ## Whether to let user reset their password
        require_same_device: bool
          ## Require the user to be on the same device
          ## that they used to request the reset password link
        require_same_ip: bool
          ## Require the user to be on the same IP
          ## that they used to create the account.

      ConfigHttpAuthentication* = object
        enable_multiple_device_sessions*: bool = true
          ## Allow multiple devices to be authenticated
          ## using the same account at the same time.
        enable_remember_me*: bool = true
          ## Allow the user to check the `remember me`
          ## checkbox to keep them logged in.
        case enable_2fa: bool
          # Enable two factor authentication.
          of false: discard
          of true:
            discard # todo
        reset_password: ConfigHttpAuthenticationResetPassword
          ## Configuration for the reset password
          ## process. This is used to send a reset password
          ## email to the user.
      
      ConfigHttpRegistration* = object
        enable: bool = true
          # Whether to enable user registration
        error_message_prevent_enumeration: bool
          # Prevents user enumeration by returning the same
          # messages for most failed/success registration attempts.
      
      ConfigHttpSessionCookie* = object
        name: string = "ssid"
          # The name of the session cookie.
        domain: string = "127.0.0.1"
          # The domain of the session cookie.
        expiration: Option[DateTime] 
          # The expiration time of the session cookie.
          # if this is set to `none(DateTime)` the `ssid`
          # cookie will be a session-based cookie and it
          # will be deleted when the browser is closed.

      ConfigHttpSession* = object
        expiration: DateTime
        session_cookie: ConfigHttpSessionCookie
          # Configuration for the session cookie.
        authentication: ConfigHttpAuthentication
          # Configuration for the authentication process.
        registration: ConfigHttpRegistration
          # Configuration for the registration process.

      # Session
      Notification* = string
      CSRFFormIdentifier* = string
        # A unique identifier for the CSRF token.
        # This is used to identify the form that the
        # CSRF token is associated with. Usually
        # this is the form action URL.

      UserSessionType = enum
        sessionTypeDefault
          # A temporary session that will be
          # deleted after a certain time
        sessionTypeRememberMe
          # A session that will be preserved
          # until the user logs out or the session
          # is deleted by the server.

      UserSessionObj* = ref object
        `type`: UserSessionType
        id: string
          # A unique NanoID that that represents the user session
          # the id can be regenerated by the server when the user session renews
          # (in case the session type is set as `sessionTypeRememberMe`)
        backend: CookiesTable = CookiesTable()
          # A `CookiesTable` for holding backend cookies.
        client: CookiesTable = CookiesTable()
          # A public `CookiesTable` for holding client cookies that will be
          # sent within the response.
        notifications: Table[string, seq[Notification]]
          # A table that holds flash bag notification messages.
          # This is useful for displaying notification messages
          # after a redirect, or a submitted form
        created, lastAccess: DateTime
        hasExpired: bool
          # Marks `UserSessionObj` as expired before deleting it.
          # Expired sessions are cleared by the SessionCleaner
          # in a separate process
        payload: JsonNode
          # A JSON object that can be used to store
          # any payload related to the current user session.
        rememberToken: string
          # generated when user checks the `remember me`
          # checkbox to keep it logged in until they log out or the session is deleted by the server.
        csrfSecretKey: string
          # A secret key used to generate CSRF tokens. This key is unique for each
          # session and is used to create HMAC-based CSRF tokens.
        csrfTokens: Table[CSRFFormIdentifier, string]
          # a table that holds the generated CSRF tokens for each form identifier. 
          # this is used to validate the CSRF token when the form is submitted.

      Sessions = Table[string, UserSessionObj]

      SessionStorageType = enum
        sessionDBStorage
        sessionFileStorage

      HttpSession = object
        keypair: string
        nonce: string
          # A unique nonce used for encrypting and decrypting session
          # data when using file storage. This should be generated once and stored securely.
        storageType: SessionStorageType
          # The storage type for the sessions. This can be either `sessionDBStorage` or `sessionFileStorage`.
        sessions: Sessions = Sessions()
          # A table that holds all the active user sessions. The key is the session id.
      
      HttpSessionError* = object of CatchableError

    # forward declaration
    proc session*(): ptr HttpSession {.inline.}
    proc initSavedSessions*(instance: ptr HttpSession)

    proc newUserSession*(userData: JsonNode, reqPath: string): UserSessionObj =
      ## Creates a new session object
      assert userData.kind == JObject
      var id: string
      let instance = session()
      while true:
        id = nanoid.generate(size = 42)
        if not instance.sessions.hasKey(id): break
      let createdAt = now()
      result = UserSessionObj(
        id: id,
        created: createdAt,
        lastAccess: createdAt,
        csrfSecretKey: nanoid.generate(size = crypto_auth_hmacsha256_keybytes()),
        payload: userData
      )
      # result.backend["ssid"] = newCookie("ssid", $(userData), createdAt + 60.minutes)
      result.client["ssid"] = newCookie("ssid", id)
      instance.sessions[id] = result # store the user session

    proc addUserSessionWith(instance: ptr HttpSession,
          id: string, createdAt: DateTime, userData: JsonNode) =
      ## Creates a new session object with a custom id and createdAt time
      assert userData.kind == JObject
      let userSession = UserSessionObj(
        id: id,
        created: createdAt,
        lastAccess: createdAt,
        csrfSecretKey: nanoid.generate(size = crypto_auth_hmacsha256_keybytes()),
        payload: userData
      )
      userSession.client["ssid"] = newCookie("ssid", id)
      instance[].sessions[id] = userSession

  client do:
    import pkg/[ozark, jsony]
    from pkg/supranim/http/request import Request, getClientData, getUriPath
    from pkg/supranim/http/response import Response, addHeader
    from pkg/supranim/controller import getClientId, getSessionCookie

    import ../model/user

    proc session*(): ptr HttpSession {.inline.} =
      ## Returns the Singleton instance of HttpSession
      getHttpSessionInstance(
        proc(instance: ptr HttpSession) =
          {.gcsafe.}:
            initSavedSessions(instance)
      ) # `getHttpSessionInstance` auto generated by the service manager
  
    proc getUserSession*(req: var Request): UserSessionObj =
      ## Returns the current user session.
      let ssid = req.getClientId()
      if ssid.isSome:
        let id = ssid.get() # the session id returned by the client
        let instance = session()
        if instance.sessions.hasKey(ssid.get()):
          return instance.sessions[ssid.get()]

    proc getId*(userSession: UserSessionObj): lent string =
      ## Returns the session id
      result = userSession.id

    proc initSessionWithHeaders*(req: var Request, res: var Response): UserSessionObj = 
      ## Initializes a new `UserSession` then adds a
      ## `set-cookie` header to the next `res` Response. 
      result = newUserSession(req.getClientData(), req.getUriPath())
      let userSessionCookie: ref Cookie = result.client["ssid"]
      if userSessionCookie != nil:
        # Add `set-cookie` header to the response
        res.addHeader("set-cookie", $userSessionCookie)
      else:
        raise newException(HttpSessionError, "Could not create a new Session")

    proc destroy*(userSession: UserSessionObj, res: var Response) =
      ## Deletes the session object and overwrites the
      ## `set-cookie` header with an expired cookie.
      ## 
      ## This will delete the session cookie from backend and client
      let instance = session()
      defer:
        instance.sessions.del(userSession.id)
      var userCookie: ref Cookie = userSession.client["ssid"]
      assert userCookie != nil
      userCookie.expires()
      res.addHeader("set-cookie", $userCookie)
    
    proc checkAuthenticity*(userSession: UserSessionObj, reqPayload: JsonNode): bool =
      ## Checks if the session payload matches the request payload. This is a basic check
      ## to prevent session hijacking by comparing the session payload with the client data
      ## of the request. The session will be considered authentic if all the key-value
      ## pairs in the session payload match the corresponding key-value pairs in the request payload.
      for k, v in userSession.payload:
        if likely(reqPayload.hasKey(k)):
          if likely(hash(v.getStr()) == hash(reqPayload[k].getStr)):
            result = true
            continue # truthy. continue to check user data
          else: return false
        return false

    template withSession*(code) {.dirty.} =
      ## Template for executing a block of code
      ## that requires a user session.
      block:
        var userSession: UserSessionObj = req.getUserSession()
        if userSession == nil: # init a new session
          userSession = initSessionWithHeaders(req, res)
        else:
          if not userSession.checkAuthenticity(req.getClientData()):
            userSession = initSessionWithHeaders(req, res)
        code

    template withUserSession*(code) {.dirty.} =
      ## Template for executing a block of code that requires a user session.
      ## This template can be used inside of a `controller`/`middleware` context
      block:
        let userSession: UserSessionObj = req.getUserSession()
        if userSession != nil:
          code # execute code block

    proc isAuthenticated*(userSession: UserSessionObj): bool =
      ## Determine if the user is authenticated by
      ## performing a database query to check if the session
      ## is valid.
      withDBPool do:
        result = userSession.payload != nil
        if result:
          let anySessions = Models.table(UserSessions).selectAll()
                                  .where("session_id", userSession.id).getAll()
          result = anySessions.isEmpty() == false
          if result:
            let storedSession = anySessions.first()
            let storedPayload = fromJson(storedSession.getPayload())
            # todo check if the session has expired based on the created_at time in the database
            for k, v in storedPayload:
              if likely(userSession.payload.hasKey(k)):
                if likely(hash(v.getStr) == hash(userSession.payload[k].getStr)):
                  continue # truthy. continue to check user data
                else: return false
              return false
    
    proc isAuthenticated*(req: var Request, res: var Response): bool =
      ## Determine if the user is authenticated by
      ## performing a database query to check if the session
      ## is valid.
      withSession do:
        result = userSession.isAuthenticated()

    proc getAuthUserId*(userSession: UserSessionObj): Option[string] =
      ## Returns the user id based on the current session
      withDBPool do:
        if userSession.payload != nil:
          let anySessions = Models.table(UserSessions)
                                  .select("user_id")
                                  .where("session_id", userSession.id)
                                  .getAll()
          if not anySessions.isEmpty():
            return some(anySessions.first().getUserId())
      none(string)

    proc getCreatedAt*(userSession: UserSessionObj): DateTime =
      ## Returns the session created at time
      userSession.created

    proc initSavedSessions*(instance: ptr HttpSession) =
      ## Initializes the HttpSession service with saved sessions
      ## from the database.
      if instance[].storageType == sessionDBStorage:
        withDBPool do:
          let anySessions = Models.table(UserSessions).selectAll().getAll()
          for s in anySessions:
            try:
              let payload = fromJson(s.getPayload())
              let id = s.getSessionId()
              let createdAt = parse(s.getCreatedAt(), "yyyy-MM-dd HH:mm:sszz")
              # if the session has expired, skip it and let the SessionCleaner process handle it
              if now() - createdAt > initDuration(days = 30): continue
              addUserSessionWith(instance, id, createdAt, %*{
                  "ip": payload["ip"],
                  "platform": payload["platform"],
                  "agent": payload["agent"],
                  "sec-ch-ua": payload["sec-ch-ua"]
                })
            except JsonParsingError as e:
              echo e.msg # todo log the error somewhere and
              continue
            except TimeParseError as e:
              echo e.msg # todo log the error somewhere and
              continue

    #
    # Manage UserSession's payload
    #
    proc updatePayload*(userSession: UserSessionObj, payload: JsonNode) =
      ## Updates the session payload
      userSession.payload = payload

    proc getPayload*(userSession: UserSessionObj): JsonNode =
      ## Retrieve the session payload
      result = userSession.payload

    proc saveSession*(userSession: UserSessionObj) =
      ## Saves the current session to the database.
      withDBPool do:
        Models.table(UserSessions).insert({
          "user_id": userSession.getAuthUserId().get(""),
          "session_id": userSession.getId(),
          "payload": toJson(userSession.getPayload()),
          "created_at": $(userSession.getCreatedAt())
        }).exec()

    #
    # CSRF handlers
    #
    proc genCSRF*(userSession: UserSessionObj, id: string): string =
      ## Generates a new CSRF token for the given form identifier and stores it in the session's `csrfTokens` table.
      ## The CSRF token is generated using HMAC-SHA256 with a unique secret key for each session.
      ## 
      ## The generated token is stored in the `csrfTokens` table with the form identifier as the key.
      ## This allows for validating the token when the form is submitted.
      result = bin2hex(crypto_auth_hmacsha256(nanoid.generate(size = 8), userSession.csrfSecretKey))
      userSession.csrfTokens[id] = result

    proc validateCSRF*(userSession: UserSessionObj, id, clientToken: string): bool =
      ## Validates the CSRF token submitted by the client against the token stored in the session
      ## for the given form identifier.
      if userSession.csrfTokens.hasKey(id) and userSession.csrfTokens[id] == clientToken:
        userSession.csrfTokens.del(id) # not needed anymore
        result = true

    #
    # Flash bag notifications
    #
    template notify*(userSession: UserSessionObj, msg: string, somePath: Option[string] = none(string)) =
      ## Adds a flash message to the session. This message will be
      ## displayed in the next response. This is useful for displaying
      ## notification messages after a redirect.
      if userSession != nil:
        let path = if somePath.isSome: somePath.get() else: req.getUriPath()
        let ssid = userSession.getId
        let instance = session()
        if instance.sessions.hasKey(ssid):
          if not instance.sessions[ssid].notifications.hasKey(path):
            instance.sessions[ssid].notifications[path] = newSeq[Notification]()
          instance.sessions[ssid].notifications[path].add(msg)

    proc getNotifications*(userSession: UserSessionObj, path: string): Option[seq[string]] =
      ## Returns available flash bag notifications.
      if userSession != nil:
        let ssid = userSession.getId
        let instance = session()
        if instance.sessions.hasKey(ssid):
          if instance.sessions[ssid].notifications.hasKey(path):
            defer:
              instance.sessions[ssid].notifications.del(path)
            return some(instance.sessions[ssid].notifications[path])
      none(seq[string])
